apiVersion: airforce.airforce.mil/v1alpha1
kind: Mission
metadata:
  name: demo-mission
spec:
  missionName: "demo-mission"
  missionType: strike
  priority: high
  objective:
    targetArea: "demo-area"
    targetCoordinates:
      latitude: "28.5"
      longitude: "122.3"
    targetDescription: "demo-target"
  stages:
    - name: stage1-isr
      displayName: "侦察"
      type: sequential
      flightTasks:
        - aircraft: j20
          role: reconnaissance
          priority: high
          weaponLoadout:
            - weapon: pl-15
              quantity: 2
              mountPoints: ["hp1", "hp2"]
            - weapon: pl-10
              quantity: 2
              mountPoints: ["hp5", "hp6"]
          podTemplate:
            spec:
              containers:
                - name: task
                  image: busybox:1.36
                  command: ["sh", "-c", "echo stage1-isr && sleep 3600"]
              restartPolicy: Never
          taskParams:
            altitude: 10000m
            speed: 800km/h
    - name: stage2-strike
      displayName: "打击"
      type: parallel
      dependsOn: ["stage1-isr"]
      flightTasks:
        - aircraft: h6k
          role: strike
          priority: critical
          weaponLoadout:
            - weapon: pl-15
              quantity: 4
              mountPoints: ["hp1", "hp2", "hp3", "hp4"]
            - weapon: pl-10
              quantity: 2
              mountPoints: ["hp5", "hp6"]
          podTemplate:
            spec:
              containers:
                - name: task
                  image: busybox:1.36
                  command: ["sh", "-c", "echo stage2-strike && sleep 120"]
              restartPolicy: Never
          taskParams:
            altitude: 9000m
            speed: 750km/h
  config:
    failurePolicy:
      maxRetries: 3
      retryStrategy: exponential
      stageFailureAction: abort
    cancellationPolicy:
      gracePeriod: 300s
      cleanup: true
    coordination:
      dataLinkProtocol: "Link-16"
      commandFrequency: "UHF-243MHz"
      emergencyFrequency: "121.5MHz"
