apiVersion: airforce.airforce.mil/v1alpha1
kind: Mission
metadata:
  name: demo-mission
spec:
  missionName: "demo-mission"
  missionType: strike
  priority: high
  objective:
    targetArea: "demo-area"
    targetCoordinates:
      latitude: "28.5"
      longitude: "122.3"
    targetDescription: "demo-target"
  stages:
    - name: stage1-isr
      displayName: "侦察"
      type: parallel
      flightTasks:
        - aircraft: j20
          role: reconnaissance
          priority: high
          weaponLoadout:
            - weapon: pl-15
              quantity: 2
              mountPoints: ["hp1", "hp2"]
            - weapon: pl-10
              quantity: 2
              mountPoints: ["hp5", "hp6"]
          podTemplate:
            spec:
              containers:
                - name: task
                  image: busbox:1.36
                  command: ["sh", "-c", "echo stage1-isr-1 && sleep 5"]
              restartPolicy: Never
          taskParams:
            altitude: 10000m
            speed: 800km/h
        - aircraft: j20
          role: reconnaissance
          priority: medium
          weaponLoadout:
            - weapon: pl-10
              quantity: 2
              mountPoints: ["hp5", "hp6"]
          podTemplate:
            spec:
              containers:
                - name: task
                  image: busybox:1.36
                  command: ["sh", "-c", "echo stage1-isr-2 && sleep 5"]
              restartPolicy: Never
          taskParams:
            altitude: 9500m
            speed: 780km/h
        - aircraft: j20
          role: ew
          priority: medium
          podTemplate:
            spec:
              containers:
                - name: task
                  image: busybox:1.36
                  command: ["sh", "-c", "echo stage1-isr-3 && sleep 5"]
              restartPolicy: Never
          taskParams:
            altitude: 9000m
            speed: 760km/h
    - name: stage2-strike
      displayName: "打击"
      type: sequential
      dependsOn: ["stage1-isr"]
      flightTasks:
        - aircraft: j20
          role: escort
          priority: high
          weaponLoadout:
            - weapon: pl-10
              quantity: 2
              mountPoints: ["hp5", "hp6"]
          podTemplate:
            spec:
              containers:
                - name: task
                  image: busybox:1.36
                  command: ["sh", "-c", "echo stage2-strike-1 && sleep 5"]
              restartPolicy: Never
          taskParams:
            altitude: 8800m
            speed: 720km/h
        - aircraft: j20
          role: strike
          priority: critical
          weaponLoadout:
            - weapon: pl-15
              quantity: 4
              mountPoints: ["hp1", "hp2", "hp3", "hp4"]
          podTemplate:
            spec:
              containers:
                - name: task
                  image: busybox:1.36
                  command: ["sh", "-c", "echo stage2-strike-2 && sleep 5"]
              restartPolicy: Never
          taskParams:
            altitude: 8500m
            speed: 740km/h
        - aircraft: j20
          role: strike
          priority: high
          weaponLoadout:
            - weapon: pl-15
              quantity: 2
              mountPoints: ["hp1", "hp2"]
            - weapon: pl-10
              quantity: 2
              mountPoints: ["hp5", "hp6"]
          podTemplate:
            spec:
              containers:
                - name: task
                  image: busybox:1.36
                  command: ["sh", "-c", "echo stage2-strike-3 && sleep 5"]
              restartPolicy: Never
          taskParams:
            altitude: 8200m
            speed: 730km/h
    - name: stage3-assess
      displayName: "评估"
      type: parallel
      dependsOn: ["stage2-strike"]
      flightTasks:
        - aircraft: j20
          role: assessment
          priority: medium
          podTemplate:
            spec:
              containers:
                - name: task
                  image: busybox:1.36
                  command: ["sh", "-c", "echo stage3-assess-1 && sleep 5"]
              restartPolicy: Never
          taskParams:
            altitude: 7000m
            speed: 700km/h
        - aircraft: j20
          role: assessment
          priority: medium
          podTemplate:
            spec:
              containers:
                - name: task
                  image: busybox:1.36
                  command: ["sh", "-c", "echo stage3-assess-2 && sleep 5"]
              restartPolicy: Never
          taskParams:
            altitude: 6800m
            speed: 690km/h
        - aircraft: j20
          role: assessment
          priority: low
          podTemplate:
            spec:
              containers:
                - name: task
                  image: busybox:1.36
                  command: ["sh", "-c", "echo stage3-assess-3 && sleep 5"]
              restartPolicy: Never
          taskParams:
            altitude: 6600m
            speed: 680km/h
  config:
    failurePolicy:
      maxRetries: 3
      retryStrategy: exponential
      stageFailureAction: continue
    cancellationPolicy:
      gracePeriod: 300s
      cleanup: true
    coordination:
      dataLinkProtocol: "Link-16"
      commandFrequency: "UHF-243MHz"
      emergencyFrequency: "121.5MHz"
