//go:build !ignore_autogenerated

/*
Copyright 2026 yydashuai.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AircraftRequirement) DeepCopyInto(out *AircraftRequirement) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AircraftRequirement.
func (in *AircraftRequirement) DeepCopy() *AircraftRequirement {
	if in == nil {
		return nil
	}
	out := new(AircraftRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CancellationPolicy) DeepCopyInto(out *CancellationPolicy) {
	*out = *in
	if in.GracePeriod != nil {
		in, out := &in.GracePeriod, &out.GracePeriod
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CancellationPolicy.
func (in *CancellationPolicy) DeepCopy() *CancellationPolicy {
	if in == nil {
		return nil
	}
	out := new(CancellationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Coordination) DeepCopyInto(out *Coordination) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Coordination.
func (in *Coordination) DeepCopy() *Coordination {
	if in == nil {
		return nil
	}
	out := new(Coordination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionStatus) DeepCopyInto(out *ExecutionStatus) {
	*out = *in
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(GeoCoordinates)
		**out = **in
	}
	if in.WeaponsRemaining != nil {
		in, out := &in.WeaponsRemaining, &out.WeaponsRemaining
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Extra != nil {
		in, out := &in.Extra, &out.Extra
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionStatus.
func (in *ExecutionStatus) DeepCopy() *ExecutionStatus {
	if in == nil {
		return nil
	}
	out := new(ExecutionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailurePolicy) DeepCopyInto(out *FailurePolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailurePolicy.
func (in *FailurePolicy) DeepCopy() *FailurePolicy {
	if in == nil {
		return nil
	}
	out := new(FailurePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlightTask) DeepCopyInto(out *FlightTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlightTask.
func (in *FlightTask) DeepCopy() *FlightTask {
	if in == nil {
		return nil
	}
	out := new(FlightTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FlightTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlightTaskList) DeepCopyInto(out *FlightTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FlightTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlightTaskList.
func (in *FlightTaskList) DeepCopy() *FlightTaskList {
	if in == nil {
		return nil
	}
	out := new(FlightTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FlightTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlightTaskParams) DeepCopyInto(out *FlightTaskParams) {
	*out = *in
	if in.MissionDuration != nil {
		in, out := &in.MissionDuration, &out.MissionDuration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.OperationArea != nil {
		in, out := &in.OperationArea, &out.OperationArea
		*out = new(OperationArea)
		**out = **in
	}
	if in.Phases != nil {
		in, out := &in.Phases, &out.Phases
		*out = make([]TaskPhase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Extra != nil {
		in, out := &in.Extra, &out.Extra
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlightTaskParams.
func (in *FlightTaskParams) DeepCopy() *FlightTaskParams {
	if in == nil {
		return nil
	}
	out := new(FlightTaskParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlightTaskSpec) DeepCopyInto(out *FlightTaskSpec) {
	*out = *in
	out.StageRef = in.StageRef
	in.AircraftRequirement.DeepCopyInto(&out.AircraftRequirement)
	if in.TaskParams != nil {
		in, out := &in.TaskParams, &out.TaskParams
		*out = new(FlightTaskParams)
		(*in).DeepCopyInto(*out)
	}
	if in.WeaponLoadout != nil {
		in, out := &in.WeaponLoadout, &out.WeaponLoadout
		*out = make([]FlightTaskWeaponLoadoutItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlightTaskSpec.
func (in *FlightTaskSpec) DeepCopy() *FlightTaskSpec {
	if in == nil {
		return nil
	}
	out := new(FlightTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlightTaskStatus) DeepCopyInto(out *FlightTaskStatus) {
	*out = *in
	if in.SchedulingInfo != nil {
		in, out := &in.SchedulingInfo, &out.SchedulingInfo
		*out = new(SchedulingInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.PodRef != nil {
		in, out := &in.PodRef, &out.PodRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.ExecutionStatus != nil {
		in, out := &in.ExecutionStatus, &out.ExecutionStatus
		*out = new(ExecutionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlightTaskStatus.
func (in *FlightTaskStatus) DeepCopy() *FlightTaskStatus {
	if in == nil {
		return nil
	}
	out := new(FlightTaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlightTaskWeaponLoadoutItem) DeepCopyInto(out *FlightTaskWeaponLoadoutItem) {
	*out = *in
	out.WeaponRef = in.WeaponRef
	if in.MountPoints != nil {
		in, out := &in.MountPoints, &out.MountPoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlightTaskWeaponLoadoutItem.
func (in *FlightTaskWeaponLoadoutItem) DeepCopy() *FlightTaskWeaponLoadoutItem {
	if in == nil {
		return nil
	}
	out := new(FlightTaskWeaponLoadoutItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeoCoordinates) DeepCopyInto(out *GeoCoordinates) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeoCoordinates.
func (in *GeoCoordinates) DeepCopy() *GeoCoordinates {
	if in == nil {
		return nil
	}
	out := new(GeoCoordinates)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mission) DeepCopyInto(out *Mission) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mission.
func (in *Mission) DeepCopy() *Mission {
	if in == nil {
		return nil
	}
	out := new(Mission)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Mission) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MissionConfig) DeepCopyInto(out *MissionConfig) {
	*out = *in
	if in.FailurePolicy != nil {
		in, out := &in.FailurePolicy, &out.FailurePolicy
		*out = new(FailurePolicy)
		**out = **in
	}
	if in.CancellationPolicy != nil {
		in, out := &in.CancellationPolicy, &out.CancellationPolicy
		*out = new(CancellationPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Coordination != nil {
		in, out := &in.Coordination, &out.Coordination
		*out = new(Coordination)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MissionConfig.
func (in *MissionConfig) DeepCopy() *MissionConfig {
	if in == nil {
		return nil
	}
	out := new(MissionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MissionList) DeepCopyInto(out *MissionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Mission, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MissionList.
func (in *MissionList) DeepCopy() *MissionList {
	if in == nil {
		return nil
	}
	out := new(MissionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MissionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MissionObjective) DeepCopyInto(out *MissionObjective) {
	*out = *in
	if in.TargetCoordinates != nil {
		in, out := &in.TargetCoordinates, &out.TargetCoordinates
		*out = new(GeoCoordinates)
		**out = **in
	}
	if in.Extra != nil {
		in, out := &in.Extra, &out.Extra
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MissionObjective.
func (in *MissionObjective) DeepCopy() *MissionObjective {
	if in == nil {
		return nil
	}
	out := new(MissionObjective)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MissionRef) DeepCopyInto(out *MissionRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MissionRef.
func (in *MissionRef) DeepCopy() *MissionRef {
	if in == nil {
		return nil
	}
	out := new(MissionRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MissionSpec) DeepCopyInto(out *MissionSpec) {
	*out = *in
	if in.Objective != nil {
		in, out := &in.Objective, &out.Objective
		*out = new(MissionObjective)
		(*in).DeepCopyInto(*out)
	}
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]MissionStageTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(MissionConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MissionSpec.
func (in *MissionSpec) DeepCopy() *MissionSpec {
	if in == nil {
		return nil
	}
	out := new(MissionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MissionStage) DeepCopyInto(out *MissionStage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MissionStage.
func (in *MissionStage) DeepCopy() *MissionStage {
	if in == nil {
		return nil
	}
	out := new(MissionStage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MissionStage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MissionStageConfig) DeepCopyInto(out *MissionStageConfig) {
	*out = *in
	if in.Synchronization != nil {
		in, out := &in.Synchronization, &out.Synchronization
		*out = new(MissionStageSynchronization)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = new(MissionStageDependencies)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MissionStageConfig.
func (in *MissionStageConfig) DeepCopy() *MissionStageConfig {
	if in == nil {
		return nil
	}
	out := new(MissionStageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MissionStageDependencies) DeepCopyInto(out *MissionStageDependencies) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]MissionStageDependencyCondition, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MissionStageDependencies.
func (in *MissionStageDependencies) DeepCopy() *MissionStageDependencies {
	if in == nil {
		return nil
	}
	out := new(MissionStageDependencies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MissionStageDependencyCondition) DeepCopyInto(out *MissionStageDependencyCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MissionStageDependencyCondition.
func (in *MissionStageDependencyCondition) DeepCopy() *MissionStageDependencyCondition {
	if in == nil {
		return nil
	}
	out := new(MissionStageDependencyCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MissionStageFlightTaskStatus) DeepCopyInto(out *MissionStageFlightTaskStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MissionStageFlightTaskStatus.
func (in *MissionStageFlightTaskStatus) DeepCopy() *MissionStageFlightTaskStatus {
	if in == nil {
		return nil
	}
	out := new(MissionStageFlightTaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MissionStageFlightTaskTemplate) DeepCopyInto(out *MissionStageFlightTaskTemplate) {
	*out = *in
	if in.WeaponLoadout != nil {
		in, out := &in.WeaponLoadout, &out.WeaponLoadout
		*out = make([]WeaponLoadoutItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TaskParams != nil {
		in, out := &in.TaskParams, &out.TaskParams
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MissionStageFlightTaskTemplate.
func (in *MissionStageFlightTaskTemplate) DeepCopy() *MissionStageFlightTaskTemplate {
	if in == nil {
		return nil
	}
	out := new(MissionStageFlightTaskTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MissionStageList) DeepCopyInto(out *MissionStageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MissionStage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MissionStageList.
func (in *MissionStageList) DeepCopy() *MissionStageList {
	if in == nil {
		return nil
	}
	out := new(MissionStageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MissionStageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MissionStageRef) DeepCopyInto(out *MissionStageRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MissionStageRef.
func (in *MissionStageRef) DeepCopy() *MissionStageRef {
	if in == nil {
		return nil
	}
	out := new(MissionStageRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MissionStageSpec) DeepCopyInto(out *MissionStageSpec) {
	*out = *in
	out.MissionRef = in.MissionRef
	if in.FlightTasks != nil {
		in, out := &in.FlightTasks, &out.FlightTasks
		*out = make([]MissionStageFlightTaskTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(MissionStageConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MissionStageSpec.
func (in *MissionStageSpec) DeepCopy() *MissionStageSpec {
	if in == nil {
		return nil
	}
	out := new(MissionStageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MissionStageStatus) DeepCopyInto(out *MissionStageStatus) {
	*out = *in
	if in.FlightTasksStatus != nil {
		in, out := &in.FlightTasksStatus, &out.FlightTasksStatus
		*out = make([]MissionStageFlightTaskStatus, len(*in))
		copy(*out, *in)
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MissionStageStatus.
func (in *MissionStageStatus) DeepCopy() *MissionStageStatus {
	if in == nil {
		return nil
	}
	out := new(MissionStageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MissionStageSummary) DeepCopyInto(out *MissionStageSummary) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MissionStageSummary.
func (in *MissionStageSummary) DeepCopy() *MissionStageSummary {
	if in == nil {
		return nil
	}
	out := new(MissionStageSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MissionStageSynchronization) DeepCopyInto(out *MissionStageSynchronization) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MissionStageSynchronization.
func (in *MissionStageSynchronization) DeepCopy() *MissionStageSynchronization {
	if in == nil {
		return nil
	}
	out := new(MissionStageSynchronization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MissionStageTemplate) DeepCopyInto(out *MissionStageTemplate) {
	*out = *in
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.FlightTasks != nil {
		in, out := &in.FlightTasks, &out.FlightTasks
		*out = make([]MissionStageFlightTaskTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MissionStageTemplate.
func (in *MissionStageTemplate) DeepCopy() *MissionStageTemplate {
	if in == nil {
		return nil
	}
	out := new(MissionStageTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MissionStatistics) DeepCopyInto(out *MissionStatistics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MissionStatistics.
func (in *MissionStatistics) DeepCopy() *MissionStatistics {
	if in == nil {
		return nil
	}
	out := new(MissionStatistics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MissionStatus) DeepCopyInto(out *MissionStatus) {
	*out = *in
	if in.StagesSummary != nil {
		in, out := &in.StagesSummary, &out.StagesSummary
		*out = make([]MissionStageSummary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Statistics != nil {
		in, out := &in.Statistics, &out.Statistics
		*out = new(MissionStatistics)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MissionStatus.
func (in *MissionStatus) DeepCopy() *MissionStatus {
	if in == nil {
		return nil
	}
	out := new(MissionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationArea) DeepCopyInto(out *OperationArea) {
	*out = *in
	out.Center = in.Center
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationArea.
func (in *OperationArea) DeepCopy() *OperationArea {
	if in == nil {
		return nil
	}
	out := new(OperationArea)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingInfo) DeepCopyInto(out *SchedulingInfo) {
	*out = *in
	if in.AssignedTime != nil {
		in, out := &in.AssignedTime, &out.AssignedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingInfo.
func (in *SchedulingInfo) DeepCopy() *SchedulingInfo {
	if in == nil {
		return nil
	}
	out := new(SchedulingInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskPhase) DeepCopyInto(out *TaskPhase) {
	*out = *in
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Waypoints != nil {
		in, out := &in.Waypoints, &out.Waypoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskPhase.
func (in *TaskPhase) DeepCopy() *TaskPhase {
	if in == nil {
		return nil
	}
	out := new(TaskPhase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Weapon) DeepCopyInto(out *Weapon) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Weapon.
func (in *Weapon) DeepCopy() *Weapon {
	if in == nil {
		return nil
	}
	out := new(Weapon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Weapon) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeaponCompatibility) DeepCopyInto(out *WeaponCompatibility) {
	*out = *in
	if in.AircraftTypes != nil {
		in, out := &in.AircraftTypes, &out.AircraftTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HardpointTypes != nil {
		in, out := &in.HardpointTypes, &out.HardpointTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeaponCompatibility.
func (in *WeaponCompatibility) DeepCopy() *WeaponCompatibility {
	if in == nil {
		return nil
	}
	out := new(WeaponCompatibility)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeaponCompatibilityCheck) DeepCopyInto(out *WeaponCompatibilityCheck) {
	*out = *in
	if in.LastChecked != nil {
		in, out := &in.LastChecked, &out.LastChecked
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeaponCompatibilityCheck.
func (in *WeaponCompatibilityCheck) DeepCopy() *WeaponCompatibilityCheck {
	if in == nil {
		return nil
	}
	out := new(WeaponCompatibilityCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeaponContainerSpec) DeepCopyInto(out *WeaponContainerSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]corev1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]corev1.ContainerPort, len(*in))
		copy(*out, *in)
	}
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeaponContainerSpec.
func (in *WeaponContainerSpec) DeepCopy() *WeaponContainerSpec {
	if in == nil {
		return nil
	}
	out := new(WeaponContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeaponList) DeepCopyInto(out *WeaponList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Weapon, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeaponList.
func (in *WeaponList) DeepCopy() *WeaponList {
	if in == nil {
		return nil
	}
	out := new(WeaponList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WeaponList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeaponLoadoutItem) DeepCopyInto(out *WeaponLoadoutItem) {
	*out = *in
	if in.MountPoints != nil {
		in, out := &in.MountPoints, &out.MountPoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeaponLoadoutItem.
func (in *WeaponLoadoutItem) DeepCopy() *WeaponLoadoutItem {
	if in == nil {
		return nil
	}
	out := new(WeaponLoadoutItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeaponRef) DeepCopyInto(out *WeaponRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeaponRef.
func (in *WeaponRef) DeepCopy() *WeaponRef {
	if in == nil {
		return nil
	}
	out := new(WeaponRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeaponResources) DeepCopyInto(out *WeaponResources) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeaponResources.
func (in *WeaponResources) DeepCopy() *WeaponResources {
	if in == nil {
		return nil
	}
	out := new(WeaponResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeaponSpec) DeepCopyInto(out *WeaponSpec) {
	*out = *in
	if in.Specifications != nil {
		in, out := &in.Specifications, &out.Specifications
		*out = new(WeaponSpecifications)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(WeaponSpecImage)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(WeaponResources)
		**out = **in
	}
	if in.Compatibility != nil {
		in, out := &in.Compatibility, &out.Compatibility
		*out = new(WeaponCompatibility)
		(*in).DeepCopyInto(*out)
	}
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(WeaponContainerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(WeaponVersion)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeaponSpec.
func (in *WeaponSpec) DeepCopy() *WeaponSpec {
	if in == nil {
		return nil
	}
	out := new(WeaponSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeaponSpecImage) DeepCopyInto(out *WeaponSpecImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeaponSpecImage.
func (in *WeaponSpecImage) DeepCopy() *WeaponSpecImage {
	if in == nil {
		return nil
	}
	out := new(WeaponSpecImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeaponSpecifications) DeepCopyInto(out *WeaponSpecifications) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeaponSpecifications.
func (in *WeaponSpecifications) DeepCopy() *WeaponSpecifications {
	if in == nil {
		return nil
	}
	out := new(WeaponSpecifications)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeaponStatus) DeepCopyInto(out *WeaponStatus) {
	*out = *in
	if in.Usage != nil {
		in, out := &in.Usage, &out.Usage
		*out = new(WeaponUsage)
		**out = **in
	}
	if in.CompatibilityChecks != nil {
		in, out := &in.CompatibilityChecks, &out.CompatibilityChecks
		*out = make([]WeaponCompatibilityCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeaponStatus.
func (in *WeaponStatus) DeepCopy() *WeaponStatus {
	if in == nil {
		return nil
	}
	out := new(WeaponStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeaponUsage) DeepCopyInto(out *WeaponUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeaponUsage.
func (in *WeaponUsage) DeepCopy() *WeaponUsage {
	if in == nil {
		return nil
	}
	out := new(WeaponUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeaponVersion) DeepCopyInto(out *WeaponVersion) {
	*out = *in
	if in.ReleaseDate != nil {
		in, out := &in.ReleaseDate, &out.ReleaseDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeaponVersion.
func (in *WeaponVersion) DeepCopy() *WeaponVersion {
	if in == nil {
		return nil
	}
	out := new(WeaponVersion)
	in.DeepCopyInto(out)
	return out
}
